const data = {
  products: [
    {
      _id: 1,
      name: "Slim Fit",
      category: "Shirts",
      image: "./images/slim2.jpg",
      brand: "TM Lewin",
      rating: 4.5,
      numReviews: 10,
      price: 120,
      description: "High Quality Product",
    },
    {
      _id: 2,
      name: "Gucci Slim Pants",
      category: "Pants",
      image: "./images/pant6.jpg",
      brand: "Gucci",
      rating: 4.2,
      numReviews: 10,
      price: 110,
      description: "High Quality Product",
    },
    {
      _id: 3,
      name: "Prada Slim Fit",
      category: "Shirts",
      image: "./images/slim4.jpg",
      brand: "Prada",
      rating: 4.6,
      numReviews: 10,
      price: 124,
      description: "High Quality Product",
    },
    {
      _id: 4,
      name: "Puma Slim Pants",
      category: "Pants",
      image: "./images/pant8.jpg",
      brand: "Puma",
      rating: 4.5,
      numReviews: 12,
      price: 122,
      description: "High Quality Product",
    },
    {
      _id: 5,
      name: "Nike Slim Fit",
      category: "Shirts",
      image: "./images/slim4.jpg",
      brand: "Nike",
      rating: 4.4,
      numReviews: 11,
      price: 125,
      description: "High Quality Product",
    },
    {
      _id: 6,
      name: "Addidas Slim Pants",
      category: "Pants",
      image: "./images/pant3.jpg",
      brand: "Addidas",
      rating: 4.8,
      numReviews: 17,
      price: 127,
      description: "High Quality Product",
    },
  ],
};

export default data;
