import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Abdul",
      email: "abdul@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Wuyep",
      email: "wuyep@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Slim Fit",
      category: "Shirts",
      image: "../images/slim2.jpg",
      brand: "TM Lewin",
      rating: 2.5,
      numReviews: 10,
      price: 120,
      countInStock: 7,
      description: "High Quality Product",
    },
    {
      name: "Gucci Slim Pants",
      category: "Pants",
      image: "../images/pant6.jpg",
      brand: "Gucci",
      rating: 3.2,
      numReviews: 10,
      price: 110,
      countInStock: 5,
      description: "High Quality Product",
    },
    {
      name: "Prada Slim Fit",
      category: "Shirts",
      image: "../images/slim4.jpg",
      brand: "Prada",
      rating: 4.6,
      numReviews: 10,
      price: 124,
      countInStock: 0,
      description: "High Quality Product",
    },
    {
      name: "Puma Slim Pants",
      category: "Pants",
      image: "../images/pant8.jpg",
      brand: "Puma",
      rating: 1.5,
      numReviews: 12,
      price: 122,
      countInStock: 2,
      description: "High Quality Product",
    },
    {
      name: "Nike Slim Fit",
      category: "Shirts",
      image: "../images/slim4.jpg",
      brand: "Nike",
      rating: 4,
      numReviews: 11,
      price: 125,
      countInStock: 0,
      description: "High Quality Product",
    },
    {
      name: "Addidas Slim Pants",
      category: "Pants",
      image: "../images/pant3.jpg",
      brand: "Addidas",
      rating: 0.7,
      numReviews: 17,
      price: 127,
      countInStock: 12,
      description: "High Quality Product",
    },
  ],
};

export default data;
